### ISSUE TITLE
Create a UI Configuration section to the main ConfigMap

### ISSUE THREAD

**Issue by mroman-redhat** [opendatahub-io/jupyterhub-singleuser-profiles#90]
To be able to configure the UI to provide only the neccessary information and in a correct manner, a configuration structure needs to be applied such as:

```
images:
  visible: False
gpu:
  limit: 4
  style: "input"
---------------- or
gpu:
  style: "dropdown"
  values:
    - 0
    - 2
    - 4
---------------- or
gpu:
  style: "checkbox"
envvars:
  style: "limited"/"unlimited"
  variables(if limited):
    - "example1"
    - "example2"
```

That is to say, the admin should be able to set whether a component is visible, what style it has (if applicable). Environment variables could be limited for example and only pre-written, GPU could be set by either a dropdown, checkbox or input. And any component could be set to not appear in the UI if neccessary.

**Comment by vpavlin** [comment]
I would replace `visible` with `enabled`

For the sake of parsing, it might be better to do something like this:

```
ui:
 gpuConfig:
  type: checkbox
  gpuCheckbox:
    value: 1
```

and

```
gpuConfig:
  type: dropdown
  gpuDropdown:
    range:
      start: 0
      end: 10
```

This way we can have classes which parse and validate each part of the config so that we don't get into a lot of mess with if/else
